export enum IndicadorEnum {
    TOTAL_DE_SOLICITACOES = 1,
    ATRASADAS = 2,
    ENCERRADAS_DENTRO_DA_DATA_ALVO = 3,
    ENCERRADAS_FORA_DA_DATA_ALVO = 4,
    TEMPO_MEDIO_DE_ATENIDMENTO = 5,
    SATISFACAO_MEDIA = 6,
    TOTAL_DE_ENCERRADAS = 7
}